### ISSUE TITLE
can't run on NodeJS 8.0 due to argument spread operator (...)

### ISSUE THREAD

**Issue by niksauer** [irhc/js-logging#5]
/home/ubuntu/Calendar-2.0/node_modules/js-logging/js-logging.umd.js:382
                this[title] = function (...args) {
                                        ^^^

SyntaxError: Unexpected token ...
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/ubuntu/Calendar-2.0/src/backend/services/user.js:41:14)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)

**Comment by irhc** [comment]
Can you give a small example? 
I have no problems with nodejs 8.1.

Anyway, if you can't use the spread operator, you can replace row 382-384 in js-logging.umd.js with
```javascript
this[title] = function () {
return log(options, i, title, format, needstack, filters, arguments);
};
```
but you must insert the following line at the beginning of the log function
```javascript
args = Array.prototype.slice.call(args);
```
